import fs from 'node:fs'

import FormData from 'form-data'

import { Tool } from '@sdk/base-tool'
import { ToolkitConfig } from '@sdk/toolkit-config'
import { Network } from '@sdk/network'

export default class OpenAIAudioTool extends Tool {
  private static readonly TOOLKIT = 'music_audio'
  private readonly config: ReturnType<typeof ToolkitConfig.load>

  constructor() {
    super()
    this.config = ToolkitConfig.load(OpenAIAudioTool.TOOLKIT, this.toolName)
  }

  get toolName(): string {
    // Use the actual config name for toolkit lookup
    return 'openai_audio'
  }

  get toolkit(): string {
    return OpenAIAudioTool.TOOLKIT
  }

  get description(): string {
    return this.config['description']
  }

  /**
   * Transcribe audio to a file using OpenAI's audio transcription API via SDK Network
   * @param inputPath Path to the audio file to transcribe
   * @param outputPath Path to save the plain text transcription
   * @param apiKey OpenAI API key
   * @param model Transcription model (e.g. 'whisper-1')
   */
  async transcribeToFile(
    inputPath: string,
    outputPath: string,
    apiKey: string,
    model = 'whisper-1'
  ): Promise<string> {
    if (!apiKey) {
      throw new Error('OpenAI API key is missing')
    }

    const form = new FormData()
    form.append('file', fs.createReadStream(inputPath))
    form.append('model', model)
    form.append('response_format', 'text')

    const network = new Network({ baseURL: 'https://api.openai.com' })
    const response = await network.request<string>({
      url: '/v1/audio/transcriptions',
      method: 'POST',
      // Pass FormData directly so axios handles multipart body
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      data: form as any,
      headers: {
        Authorization: `Bearer ${apiKey}`,
        // Include multipart boundary header generated by form-data
        ...form.getHeaders()
      }
    })

    await fs.promises.writeFile(
      outputPath,
      response.data as unknown as string,
      'utf8'
    )

    return outputPath
  }
}
